[package]
name = "pack_combine"
version = "0.2.0"
authors = ["Kyle Clemens <git@kyleclemens.com>"]
edition = "2018"

[dependencies]
failure = "0.1"
hex = "0.3"
parking_lot = "0.7"
rayon = "1"
sha2 = "0.8"
walkdir = "2"
